[custom]

;1. 域名组

;用于自定义规则的选项 会覆盖 主程序目录中的配置文件 里的内容
;Ruleset addresses, supports local files/URL
;Format: Group name,[type:]URL[,interval]
;        Group name,[]Rule
;where "type" supports the following value: surge, quanx, clash-domain, clash-ipcidr, clash-classic
;type defaults to surge if omitted
;ruleset=DIRECT,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Unbreak.list,86400
;ruleset=🎯 全球直连,rules/LocalAreaNetwork.list
;ruleset=DIRECT,surge:rules/LocalAreaNetwork.list
;ruleset=Advertising,quanx:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Guard/Advertising.list,86400
;ruleset=Domestic Services,clash-domain:https://ruleset.dev/clash_domestic_services_domains,86400
;ruleset=Domestic Services,clash-ipcidr:https://ruleset.dev/clash_domestic_services_ips,86400
;ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml,86400
;ruleset=🎯 全球直连,[]GEOIP,CN
;ruleset=🐟 漏网之鱼,[]FINAL

; Special👍
ruleset=👌 Special-Direct,clash-classic:https://gitee.com/UncleC0der/agw-config/raw/dev/Rule/Clash/Special-D.yaml
ruleset=👈 Special-Proxy,clash-classic:https://gitee.com/UncleC0der/agw-config/raw/dev/Rule/Clash/Special-P.yaml
; 指定
ruleset=🇺🇲 美国站点,clash-classic:https://gitee.com/UncleC0der/agw-config/raw/dev/Rule/Clash/Carrier/US-Carrier.yaml
ruleset=🇬🇧 英国站点,clash-classic:https://gitee.com/UncleC0der/agw-config/raw/dev/Rule/Clash/Carrier/UK-Carrier.yaml
ruleset=🇬🇧 英国站点,https://raw.githubusercontent.com/iniwex5/tools/refs/heads/main/rules/UK.list
ruleset=🇭🇰 香港站点,clash-classic:https://gitee.com/UncleC0der/agw-config/raw/dev/Rule/Clash/Carrier/HK-Carrier.yaml
; 
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🆎 AdBlock,clash-classic:https://raw.dler.io/dler-io/Rules/main/Clash/Provider/AdBlock.yaml
; ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list

; Bitcoin
ruleset=💰 Bybit,clash-classic:https://gitee.com/UncleC0der/agw-config/raw/dev/Rule/Clash/Bitcoin/Bybit.yaml

; AI
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/ChatGPT.list
ruleset=✨ AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=✨ AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=✨ AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI2.list
ruleset=✨ AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/MetaAi.list
ruleset=✨ AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=✨ AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list

; GitHub
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list

;Apple
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list

; Microsoft
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
; Google
ruleset=🧩 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🧩 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🧩 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=🧩 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🧩 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleEarth.list
ruleset=🧩 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

; 社交
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🙋 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🕊️ Twitter(X),https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=🗣️ Meta,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list
ruleset=🗣️ Meta,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Whatsapp/Whatsapp.yaml
ruleset=💁 Line,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.yaml

; Game
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🕹️ Game,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list

; 流媒体
ruleset=🎞️ YouTube,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/YouTube.list
ruleset=🎞️ YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📺 Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎬 HBO MAX,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list

; PT
ruleset=🚀 PT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🚀 PT,https://raw.githubusercontent.com/iniwex5/tools/refs/heads/main/rules/PT.list


; Other
ruleset=⏱️ 检测,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list

;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


;2、策略组（域名组-节点组）
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🤖 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🇺🇲 美国站点`select`[]🇺🇲 美国手动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇬🇧 英国站点`select`[]🇬🇧 英国手动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇭🇰 香港站点`select`[]🇭🇰 香港手动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=👌 Special-Direct`select`[]DIRECT`[]👉 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=👈 Special-Proxy`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=💰 Bybit`select`[]DIRECT`[]👉 手动切换`[]🇭🇰 香港节点`[]🇭🇰 香港手动`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇬🇧 英国手动`[]🇩🇪 德国手动`[]🇷🇺 俄罗斯节点
custom_proxy_group=✨ AI`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=📘 GitHub`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🧩 Google`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🙋 Telegram`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🕊️ Twitter(X)`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🗣️ Meta`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
; custom_proxy_group=💁 WhatApp`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=💁 Line`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🎮 Steam`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🕹️ Game`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🎞️ YouTube`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=📺 Disney`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🎬 HBO MAX`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🎵 Spotify`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🚀 PT`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=⏱️ 检测`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🌍 国外`select`[]🚀 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点

;3、节点组
custom_proxy_group=🚀 节点选择`select`[]🤖 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🇨🇦 加拿大节点`[]🇸🇬 新加坡节点`[]🇸🇬 东南亚节点`[]🇮🇳 印度节点`[]🇹🇷 土耳其节点`[]🇧🇷 南美节点`[]🇪🇺 欧洲节点`[]🇷🇺 俄罗斯节点`[]👉 手动切换`[]DIRECT
custom_proxy_group=👉 手动切换`select`.*
custom_proxy_group=🤖 自动选择`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔯 故障转移`fallback`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港手动`select`(港|HK|hk|Hong Kong|HongKong|hongkong)
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇺🇲 美国手动`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇨🇦 加拿大节点`url-test`(加拿大)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇸🇬 东南亚节点`url-test`(新加坡|泰国|菲律宾|马来西亚)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇮🇳 印度节点`url-test`(印度)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇹🇷 土耳其节点`url-test`(土耳其)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇧🇷 南美节点`url-test`(巴西|阿根廷|尼日利亚)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇪🇺 欧洲节点`url-test`(德国|法国|英国)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇬🇧 英国手动`select`(英国)
custom_proxy_group=🇩🇪 德国手动`select`(德国)
custom_proxy_group=🇷🇺 俄罗斯节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`60,150


;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
